### ISSUE TITLE
tuniao create 创建项目失败

### ISSUE THREAD

**Issue by xkfe** [ahua666/tuniaoUI#9]
brew 安装的node和pnpm，然后使用脚手架方式创建vue3版本失败
尝试过使用gitee，npm sudo tuniao create都不行
mac版本：Ventura 13.3.1
pnpm版本：8.6.9
node版本：20.5
<img width="803" alt="image" src="https://github.com/ahua666/tuniaoUI/assets/129662190/d512660b-f0a2-4915-8385-bda79795ef6c">

**Comment by ahua666** [comment]
前往vue3仓库提交lssues  [https://github.com/tuniaoTech/tuniaoui-rc-vue3-uniapp](https://github.com/tuniaoTech/tuniaoui-rc-vue3-uniapp)
